name: Publish PyPI (Windows x86_64 For CPU)

# on:
#   push:
#     tags:
#       - 'v*'
#   workflow_dispatch:

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:  # 添加手动触发器

jobs:
  build:
    name: Build Windows wheel (CPython 3.12)
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies & build tools
        run: |
          python -m pip install -U pip wheel setuptools build delvewheel pybind11

      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. DCMAKE_BUILD_TYPE=Release
          build
          cd ..

      - name: Build wheel
        run: python -m build --wheel

      - name: Repair wheel (delvewheel)
        run: delvewheel repair -w dist dist/*.whl

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-win-cp312
          path: dist/*.whl

  upload_pypi:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheels-win-cp312
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true

      - name: Publish to download.axono.org
        env:
          URL: ${{ secrets.AXONO_URL }}
          PASS: ${{ secrets.AXONO_PASSWD }}
          DEV: cpu
          PKG: axono
        run: |
          for whl in dist/*.whl; do
            echo "Uploading $whl ..."
            echo
            curl -s -F "device=$DEV" \
                    -F "package=$PKG" \
                    -F "passwd=$PASS" \
                    -F "file=@$whl" \
                    "$URL"
            echo
          done
